spring:
  application:
    name: inventory-service
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${INVENTORY_DB_HOST:localhost}:${INVENTORY_DB_PORT:5432}/${INVENTORY_DB_NAME:inventory_db}
    username: ${INVENTORY_DB_USERNAME:inventory_user}
    password: ${INVENTORY_DB_PASSWORD:inventory_pass}
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        '[dialect]': org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true
        '[use_sql_comments]': true

# Server Configuration
server:
  port: ${SERVER_PORT:8000}
  servlet:
    context-path: /api/v1

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

# Logging Configuration
logging:
  level:
    '[com.petek.inventory_service]': INFO
    '[org.springframework.web]': DEBUG
    '[org.hibernate.SQL]': DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:h2:mem:inventory_dev
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  h2:
    console:
      enabled: true

logging:
  level:
    root: DEBUG
    '[com.petek.inventory_service]': DEBUG


