### Create Campaign

POST http://localhost:8000/api/v1/campaigns
content-type: application/json

{
    "campaignName": "Test",
    "campaignType": "BXGY_SAME_PRODUCT",
    "buyQty": 1,
    "getQty": 1,
    "startDate": "2025-09-10",
    "endDate": "2025-09-10"
}

### Get Campaign By Id

GET http://localhost:8000/api/v1/campaigns/1

### Update Campaign

PUT http://localhost:8000/api/v1/campaigns/1
content-type: application/json

{
    "campaignName": "Test",
    "buyQty": 10,
    "getQty": 10,
    "startDate": "2025-09-10",
    "endDate": "2025-09-10"
}

### Delete Campaign By Id

DELETE  http://localhost:8000/api/v1/campaigns/2