import { Injectable } from '@angular/core';
import { Product } from '../models/product.model';
import { Supplier } from '../models/supplier.model';
import { Customer } from '../models/customer.model';

@Injectable({
  providedIn: 'root'
})
export class MockDataService {
  getProducts(): Product[] {
    return [
      {
        id: 'ID-001',
        name: 'Lego Star*War edition',
        category: 'Toys',
        unit: 'pcs',
        currentStock: 1000000,
        preferredSupplierId: 'SUP-008',
        activeSupplierIds: ['SUP-003', 'SUP-001', 'SUP-008'],
        status: 'ok',
      },
      {
        id: 'ID-002',
        name: 'Alpha',
        category: 'Chemical',
        unit: 'L',
        currentStock: 2000,
        preferredSupplierId: 'SUP-002',
        activeSupplierIds: [],
        status: 'ok',
      },
      {
        id: 'ID-003',
        name: 'Beta',
        category: 'Food',
        unit: 'kg',
        currentStock: 500000,
        preferredSupplierId: 'SUP-003',
        activeSupplierIds: [],
        status: 'ok',
      },
      {
        id: 'ID-004',
        name: 'Gamma',
        category: 'Raw Material',
        unit: 'kg',
        currentStock: 230,
        preferredSupplierId: 'SUP-004',
        activeSupplierIds: [],
        status: 'ok',
      },
      {
        id: 'ID-008',
        name: 'Eta',
        category: 'Raw Material',
        unit: 'kg',
        currentStock: 90,
        preferredSupplierId: 'SUP-008',
        activeSupplierIds: [],
        status: 'warning',
      },
      {
        id: 'ID-009',
        name: 'Theta',
        category: 'Raw Material',
        unit: 'kg',
        currentStock: 10000,
        preferredSupplierId: 'SUP-009',
        activeSupplierIds: ['SUP-010'],
        status: 'warning',
      },
      {
        id: 'ID-010',
        name: 'Iota',
        category: 'Raw Material',
        unit: 'kg',
        currentStock: 8000,
        preferredSupplierId: 'SUP-010',
        activeSupplierIds: [],
        status: 'critical',
      },
      {
        id: 'ID-011',
        name: 'Kappa',
        category: 'Raw Material',
        unit: 'kg',
        currentStock: 100,
        preferredSupplierId: 'SUP-011',
        activeSupplierIds: [],
        status: 'critical',
      },
      {
        id: 'ID-012',
        name: 'PlayStation 7 Console',
        category: 'Electronics',
        unit: 'pcs',
        currentStock: 4500,
        preferredSupplierId: 'SUP-012',
        activeSupplierIds: [],
        status: 'ok',
      },
      {
        id: 'ID-013',
        name: 'Omega Oil',
        category: 'Chemical',
        unit: 'L',
        currentStock: 120,
        preferredSupplierId: 'SUP-013',
        activeSupplierIds: ['SUP-014'],
        status: 'critical',
      },
      {
        id: 'ID-014',
        name: 'Choco Deluxe Bar',
        category: 'Food',
        unit: 'pcs',
        currentStock: 75000,
        preferredSupplierId: 'SUP-014',
        activeSupplierIds: [],
        status: 'ok',
      },
      {
        id: 'ID-015',
        name: 'Steel Rods',
        category: 'Raw Material',
        unit: 'ton',
        currentStock: 320,
        preferredSupplierId: 'SUP-015',
        activeSupplierIds: [],
        status: 'warning',
      },
      {
        id: 'ID-016',
        name: 'VR Headset Ultra',
        category: 'Electronics',
        unit: 'pcs',
        currentStock: 980,
        preferredSupplierId: 'SUP-016',
        activeSupplierIds: ['SUP-018'],
        status: 'ok',
      },
      {
        id: 'ID-017',
        name: 'Luxury Sofa',
        category: 'Furniture',
        unit: 'pcs',
        currentStock: 40,
        preferredSupplierId: 'SUP-017',
        activeSupplierIds: [],
        status: 'warning',
      },
      {
        id: 'ID-018',
        name: 'Coffee Beans Premium',
        category: 'Food',
        unit: 'kg',
        currentStock: 2500,
        preferredSupplierId: 'SUP-019',
        activeSupplierIds: [],
        status: 'ok',
      },
      {
        id: 'ID-019',
        name: 'Industrial Glue X',
        category: 'Chemical',
        unit: 'L',
        currentStock: 50,
        preferredSupplierId: 'SUP-020',
        activeSupplierIds: [],
        status: 'critical',
      },
      {
        id: 'ID-020',
        name: 'Robotic Arm V2',
        category: 'Machinery',
        unit: 'pcs',
        currentStock: 12,
        preferredSupplierId: 'SUP-021',
        activeSupplierIds: [],
        status: 'warning',
      },
      {
        id: 'ID-021',
        name: 'Gaming Chair Pro',
        category: 'Furniture',
        unit: 'pcs',
        currentStock: 300,
        preferredSupplierId: 'SUP-022',
        activeSupplierIds: ['SUP-023'],
        status: 'ok',
      },
    ];
  }

  getSuppliers(): Supplier[] {
    return [
      {
        id: 'SUP-001',
        name: 'Acme Co.',
        email: 'sales@acme.com',
        phone: '+90 555 111 22 33',
        city: 'Ankara',
      },
      {
        id: 'SUP-002',
        name: 'Globex',
        email: 'info@globex.io',
        phone: '+90 555 222 33 44',
        city: 'Istanbul',
      },
      {
        id: 'SUP-003',
        name: 'Initech',
        email: 'hello@initech.com',
        phone: '+90 555 333 44 55',
        city: 'Izmir',
      },
      {
        id: 'SUP-008',
        name: 'TechCorp',
        email: 'contact@techcorp.com',
        phone: '+90 555 444 55 66',
        city: 'Bursa',
      },
      {
        id: 'SUP-009',
        name: 'Industrial Solutions',
        email: 'info@industrialsol.com',
        phone: '+90 555 555 66 77',
        city: 'Antalya',
      },
      {
        id: 'SUP-010',
        name: 'Global Supplies',
        email: 'sales@globalsupplies.com',
        phone: '+90 555 666 77 88',
        city: 'Adana',
      },
      {
        id: 'SUP-011',
        name: 'Premium Materials',
        email: 'orders@premiummaterials.com',
        phone: '+90 555 777 88 99',
        city: 'Gaziantep',
      },
      {
        id: 'SUP-012',
        name: 'Electronics Hub',
        email: 'support@electronicshub.com',
        phone: '+90 555 888 99 00',
        city: 'Konya',
      },
      {
        id: 'SUP-013',
        name: 'Chemical Corp',
        email: 'info@chemicalcorp.com',
        phone: '+90 555 999 00 11',
        city: 'Kayseri',
      },
      {
        id: 'SUP-014',
        name: 'Food Distributors',
        email: 'sales@fooddist.com',
        phone: '+90 555 000 11 22',
        city: 'Mersin',
      },
      {
        id: 'SUP-015',
        name: 'Steel Works',
        email: 'orders@steelworks.com',
        phone: '+90 555 111 33 44',
        city: 'Eskişehir',
      },
      {
        id: 'SUP-016',
        name: 'VR Technologies',
        email: 'contact@vrtech.com',
        phone: '+90 555 222 44 55',
        city: 'Trabzon',
      },
      {
        id: 'SUP-017',
        name: 'Furniture Plus',
        email: 'info@furnitureplus.com',
        phone: '+90 555 333 55 66',
        city: 'Denizli',
      },
      {
        id: 'SUP-018',
        name: 'Tech Accessories',
        email: 'sales@techacc.com',
        phone: '+90 555 444 66 77',
        city: 'Malatya',
      },
      {
        id: 'SUP-019',
        name: 'Coffee Masters',
        email: 'orders@coffeemasters.com',
        phone: '+90 555 555 77 88',
        city: 'Ordu',
      },
      {
        id: 'SUP-020',
        name: 'Industrial Chemicals',
        email: 'info@indchem.com',
        phone: '+90 555 666 88 99',
        city: 'Sivas',
      },
      {
        id: 'SUP-021',
        name: 'Robotics Inc',
        email: 'support@roboticsinc.com',
        phone: '+90 555 777 99 00',
        city: 'Çorum',
      },
      {
        id: 'SUP-022',
        name: 'Gaming Solutions',
        email: 'sales@gamingsol.com',
        phone: '+90 555 888 00 11',
        city: 'Afyon',
      },
      {
        id: 'SUP-023',
        name: 'Comfort Furniture',
        email: 'info@comfortfurn.com',
        phone: '+90 555 999 11 22',
        city: 'Manisa',
      },
    ];
  }

  getCustomers(): Customer[] {
    return [
      {
        id: 'CUST-001',
        name: 'Alice Johnson',
        segment: 'individual',
        email: 'alice.johnson@example.com',
        phone: '+90 501 111 22 33',
        city: 'Ankara',
      },
      {
        id: 'CUST-002',
        name: 'Bob Smith',
        segment: 'sme',
        email: 'bob.smith@example.com',
        phone: '+90 502 222 33 44',
        city: 'Istanbul',
      },
      {
        id: 'CUST-003',
        name: 'Clara Lee',
        segment: 'institutional',
        email: 'clara.lee@example.com',
        phone: '+90 503 333 44 55',
        city: 'Izmir',
      },
      {
        id: 'CUST-004',
        name: 'David Brown',
        segment: 'sme',
        email: 'david.brown@example.com',
        phone: '+90 504 444 55 66',
        city: 'Bursa',
      },
      {
        id: 'CUST-005',
        name: 'Eva Green',
        segment: 'individual',
        email: 'eva.green@example.com',
        phone: '+90 505 555 66 77',
        city: 'Antalya',
      },
      {
        id: 'CUST-006',
        name: 'Frank Miller',
        segment: 'sme',
        email: 'frank.miller@example.com',
        phone: '+90 506 666 77 88',
        city: 'Adana',
      },
      {
        id: 'CUST-007',
        name: 'Grace Kim',
        segment: 'institutional',
        email: 'grace.kim@example.com',
        phone: '+90 507 777 88 99',
        city: 'Gaziantep',
      },
      {
        id: 'CUST-008',
        name: 'Henry Wilson',
        segment: 'sme',
        email: 'henry.wilson@example.com',
        phone: '+90 508 888 99 00',
        city: 'Konya',
      },
      {
        id: 'CUST-009',
        name: 'Ivy Martinez',
        segment: 'individual',
        email: 'ivy.martinez@example.com',
        phone: '+90 509 999 00 11',
        city: 'Kayseri',
      },
      {
        id: 'CUST-010',
        name: 'Jack Taylor',
        segment: 'institutional',
        email: 'jack.taylor@example.com',
        phone: '+90 510 000 11 22',
        city: 'Mersin',
      },
    ];
  }
}