import { Injectable } from '@angular/core';
import { Product } from '../models/product.model';
import { Supplier } from '../models/supplier.model';
import { Customer } from '../models/customer.model';
import { Order } from '../models/order.model';
import { Campaign } from '../models/campaign.model';

@Injectable({
  providedIn: 'root',
})
export class MockDataService {
  getProducts(): Product[] {
    return [
      {
        id: 'ID-001',
        name: 'Lego Star*War edition',
        category: 'Toys',
        unit: 'pcs',
        currentStock: 1000000,
        preferredSupplierId: 'SUP-008',
        activeSupplierIds: ['SUP-003', 'SUP-001', 'SUP-008'],
        status: 'ok',
      },
      {
        id: 'ID-002',
        name: 'Alpha',
        category: 'Chemical',
        unit: 'L',
        currentStock: 2000,
        preferredSupplierId: 'SUP-002',
        activeSupplierIds: [],
        status: 'ok',
      },
      {
        id: 'ID-003',
        name: 'Beta',
        category: 'Food',
        unit: 'kg',
        currentStock: 500000,
        preferredSupplierId: 'SUP-003',
        activeSupplierIds: [],
        status: 'ok',
      },
      {
        id: 'ID-004',
        name: 'Gamma',
        category: 'Raw Material',
        unit: 'kg',
        currentStock: 230,
        preferredSupplierId: 'SUP-004',
        activeSupplierIds: [],
        status: 'ok',
      },
      {
        id: 'ID-008',
        name: 'Eta',
        category: 'Raw Material',
        unit: 'kg',
        currentStock: 90,
        preferredSupplierId: 'SUP-008',
        activeSupplierIds: [],
        status: 'warning',
      },
      {
        id: 'ID-009',
        name: 'Theta',
        category: 'Raw Material',
        unit: 'kg',
        currentStock: 10000,
        preferredSupplierId: 'SUP-009',
        activeSupplierIds: ['SUP-010'],
        status: 'warning',
      },
      {
        id: 'ID-010',
        name: 'Iota',
        category: 'Raw Material',
        unit: 'kg',
        currentStock: 8000,
        preferredSupplierId: 'SUP-010',
        activeSupplierIds: [],
        status: 'critical',
      },
      {
        id: 'ID-011',
        name: 'Kappa',
        category: 'Raw Material',
        unit: 'kg',
        currentStock: 100,
        preferredSupplierId: 'SUP-011',
        activeSupplierIds: [],
        status: 'critical',
      },
      {
        id: 'ID-012',
        name: 'PlayStation 7 Console',
        category: 'Electronics',
        unit: 'pcs',
        currentStock: 4500,
        preferredSupplierId: 'SUP-012',
        activeSupplierIds: [],
        status: 'ok',
      },
      {
        id: 'ID-013',
        name: 'Omega Oil',
        category: 'Chemical',
        unit: 'L',
        currentStock: 120,
        preferredSupplierId: 'SUP-013',
        activeSupplierIds: ['SUP-014'],
        status: 'critical',
      },
      {
        id: 'ID-014',
        name: 'Choco Deluxe Bar',
        category: 'Food',
        unit: 'pcs',
        currentStock: 75000,
        preferredSupplierId: 'SUP-014',
        activeSupplierIds: [],
        status: 'ok',
      },
      {
        id: 'ID-015',
        name: 'Steel Rods',
        category: 'Raw Material',
        unit: 'ton',
        currentStock: 320,
        preferredSupplierId: 'SUP-015',
        activeSupplierIds: [],
        status: 'warning',
      },
      {
        id: 'ID-016',
        name: 'VR Headset Ultra',
        category: 'Electronics',
        unit: 'pcs',
        currentStock: 980,
        preferredSupplierId: 'SUP-016',
        activeSupplierIds: ['SUP-018'],
        status: 'ok',
      },
      {
        id: 'ID-017',
        name: 'Luxury Sofa',
        category: 'Furniture',
        unit: 'pcs',
        currentStock: 40,
        preferredSupplierId: 'SUP-017',
        activeSupplierIds: [],
        status: 'warning',
      },
      {
        id: 'ID-018',
        name: 'Coffee Beans Premium',
        category: 'Food',
        unit: 'kg',
        currentStock: 2500,
        preferredSupplierId: 'SUP-019',
        activeSupplierIds: [],
        status: 'ok',
      },
      {
        id: 'ID-019',
        name: 'Industrial Glue X',
        category: 'Chemical',
        unit: 'L',
        currentStock: 50,
        preferredSupplierId: 'SUP-020',
        activeSupplierIds: [],
        status: 'critical',
      },
      {
        id: 'ID-020',
        name: 'Robotic Arm V2',
        category: 'Machinery',
        unit: 'pcs',
        currentStock: 12,
        preferredSupplierId: 'SUP-021',
        activeSupplierIds: [],
        status: 'warning',
      },
      {
        id: 'ID-021',
        name: 'Gaming Chair Pro',
        category: 'Furniture',
        unit: 'pcs',
        currentStock: 300,
        preferredSupplierId: 'SUP-022',
        activeSupplierIds: ['SUP-023'],
        status: 'ok',
      },
    ];
  }

  getSuppliers(): Supplier[] {
    return [
      {
        id: 'SUP-001',
        name: 'Acme Co.',
        email: 'sales@acme.com',
        phone: '+90 555 111 22 33',
        city: 'Ankara',
      },
      {
        id: 'SUP-002',
        name: 'Globex',
        email: 'info@globex.io',
        phone: '+90 555 222 33 44',
        city: 'Istanbul',
      },
      {
        id: 'SUP-003',
        name: 'Initech',
        email: 'hello@initech.com',
        phone: '+90 555 333 44 55',
        city: 'Izmir',
      },
      {
        id: 'SUP-008',
        name: 'TechCorp',
        email: 'contact@techcorp.com',
        phone: '+90 555 444 55 66',
        city: 'Bursa',
      },
      {
        id: 'SUP-009',
        name: 'Industrial Solutions',
        email: 'info@industrialsol.com',
        phone: '+90 555 555 66 77',
        city: 'Antalya',
      },
      {
        id: 'SUP-010',
        name: 'Global Supplies',
        email: 'sales@globalsupplies.com',
        phone: '+90 555 666 77 88',
        city: 'Adana',
      },
      {
        id: 'SUP-011',
        name: 'Premium Materials',
        email: 'orders@premiummaterials.com',
        phone: '+90 555 777 88 99',
        city: 'Gaziantep',
      },
      {
        id: 'SUP-012',
        name: 'Electronics Hub',
        email: 'support@electronicshub.com',
        phone: '+90 555 888 99 00',
        city: 'Konya',
      },
      {
        id: 'SUP-013',
        name: 'Chemical Corp',
        email: 'info@chemicalcorp.com',
        phone: '+90 555 999 00 11',
        city: 'Kayseri',
      },
      {
        id: 'SUP-014',
        name: 'Food Distributors',
        email: 'sales@fooddist.com',
        phone: '+90 555 000 11 22',
        city: 'Mersin',
      },
      {
        id: 'SUP-015',
        name: 'Steel Works',
        email: 'orders@steelworks.com',
        phone: '+90 555 111 33 44',
        city: 'Eskişehir',
      },
      {
        id: 'SUP-016',
        name: 'VR Technologies',
        email: 'contact@vrtech.com',
        phone: '+90 555 222 44 55',
        city: 'Trabzon',
      },
      {
        id: 'SUP-017',
        name: 'Furniture Plus',
        email: 'info@furnitureplus.com',
        phone: '+90 555 333 55 66',
        city: 'Denizli',
      },
      {
        id: 'SUP-018',
        name: 'Tech Accessories',
        email: 'sales@techacc.com',
        phone: '+90 555 444 66 77',
        city: 'Malatya',
      },
      {
        id: 'SUP-019',
        name: 'Coffee Masters',
        email: 'orders@coffeemasters.com',
        phone: '+90 555 555 77 88',
        city: 'Ordu',
      },
      {
        id: 'SUP-020',
        name: 'Industrial Chemicals',
        email: 'info@indchem.com',
        phone: '+90 555 666 88 99',
        city: 'Sivas',
      },
      {
        id: 'SUP-021',
        name: 'Robotics Inc',
        email: 'support@roboticsinc.com',
        phone: '+90 555 777 99 00',
        city: 'Çorum',
      },
      {
        id: 'SUP-022',
        name: 'Gaming Solutions',
        email: 'sales@gamingsol.com',
        phone: '+90 555 888 00 11',
        city: 'Afyon',
      },
      {
        id: 'SUP-023',
        name: 'Comfort Furniture',
        email: 'info@comfortfurn.com',
        phone: '+90 555 999 11 22',
        city: 'Manisa',
      },
    ];
  }

  getCustomers(): Customer[] {
    return [
      {
        id: 'CUST-001',
        name: 'Alice Johnson',
        segment: 'individual',
        email: 'alice.johnson@example.com',
        phone: '+90 501 111 22 33',
        city: 'Ankara',
      },
      {
        id: 'CUST-002',
        name: 'Bob Smith',
        segment: 'sme',
        email: 'bob.smith@example.com',
        phone: '+90 502 222 33 44',
        city: 'Istanbul',
      },
      {
        id: 'CUST-003',
        name: 'Clara Lee',
        segment: 'institutional',
        email: 'clara.lee@example.com',
        phone: '+90 503 333 44 55',
        city: 'Izmir',
      },
      {
        id: 'CUST-004',
        name: 'David Brown',
        segment: 'sme',
        email: 'david.brown@example.com',
        phone: '+90 504 444 55 66',
        city: 'Bursa',
      },
      {
        id: 'CUST-005',
        name: 'Eva Green',
        segment: 'individual',
        email: 'eva.green@example.com',
        phone: '+90 505 555 66 77',
        city: 'Antalya',
      },
      {
        id: 'CUST-006',
        name: 'Frank Miller',
        segment: 'sme',
        email: 'frank.miller@example.com',
        phone: '+90 506 666 77 88',
        city: 'Adana',
      },
      {
        id: 'CUST-007',
        name: 'Grace Kim',
        segment: 'institutional',
        email: 'grace.kim@example.com',
        phone: '+90 507 777 88 99',
        city: 'Gaziantep',
      },
      {
        id: 'CUST-008',
        name: 'Henry Wilson',
        segment: 'sme',
        email: 'henry.wilson@example.com',
        phone: '+90 508 888 99 00',
        city: 'Konya',
      },
      {
        id: 'CUST-009',
        name: 'Ivy Martinez',
        segment: 'individual',
        email: 'ivy.martinez@example.com',
        phone: '+90 509 999 00 11',
        city: 'Kayseri',
      },
      {
        id: 'CUST-010',
        name: 'Jack Taylor',
        segment: 'institutional',
        email: 'jack.taylor@example.com',
        phone: '+90 510 000 11 22',
        city: 'Mersin',
      },
    ];
  }

  getOrders(): Order[] {
    return [
      {
        id: 'PO-001',
        type: 'purchase',
        supplierId: 'SUP-001',
        orderDate: '2024-09-01',
        deliveryDate: '2024-09-15',
        quantity: 500,
        totalPrice: 25000,
        status: 'received',
        productId: 'ID-001',
      },
      {
        id: 'PO-002',
        type: 'purchase',
        supplierId: 'SUP-002',
        orderDate: '2024-09-03',
        deliveryDate: '2024-09-20',
        quantity: 100,
        totalPrice: 8500,
        status: 'in_transit',
        productId: 'ID-002',
      },
      {
        id: 'PO-003',
        type: 'purchase',
        supplierId: 'SUP-003',
        orderDate: '2024-09-05',
        deliveryDate: '2024-09-25',
        quantity: 200,
        totalPrice: 15000,
        status: 'placed',
        productId: 'ID-003',
      },
      {
        id: 'PO-004',
        type: 'purchase',
        supplierId: 'SUP-004',
        orderDate: '2024-08-28',
        deliveryDate: '2024-09-10',
        quantity: 50,
        totalPrice: 3200,
        status: 'canceled',
        productId: 'ID-004',
      },
      {
        id: 'SO-001',
        type: 'sales',
        customerId: 'CUST-001',
        orderDate: '2024-09-02',
        deliveryDate: '2024-09-16',
        quantity: 10,
        totalPrice: 2500,
        status: 'delivered',
        productId: 'ID-012',
      },
      {
        id: 'SO-002',
        type: 'sales',
        customerId: 'CUST-002',
        orderDate: '2024-09-04',
        deliveryDate: '2024-09-18',
        quantity: 5,
        totalPrice: 4500,
        status: 'in_transit',
        productId: 'ID-016',
      },
      {
        id: 'SO-003',
        type: 'sales',
        customerId: 'CUST-003',
        orderDate: '2024-09-06',
        deliveryDate: '2024-09-22',
        quantity: 20,
        totalPrice: 3000,
        status: 'allocated',
        productId: 'ID-014',
      },
      {
        id: 'SO-004',
        type: 'sales',
        customerId: 'CUST-004',
        orderDate: '2024-09-07',
        deliveryDate: '2024-09-25',
        quantity: 2,
        totalPrice: 800,
        status: 'pending',
        productId: 'ID-017',
      },
      {
        id: 'SO-005',
        type: 'sales',
        customerId: 'CUST-005',
        orderDate: '2024-08-30',
        deliveryDate: '2024-09-12',
        quantity: 15,
        totalPrice: 1800,
        status: 'canceled',
        productId: 'ID-018',
      },
      {
        id: 'PO-005',
        type: 'purchase',
        supplierId: 'SUP-008',
        orderDate: '2024-09-08',
        deliveryDate: '2024-09-28',
        quantity: 1000,
        totalPrice: 75000,
        status: 'placed',
        productId: 'ID-001',
      },
      {
        id: 'SO-006',
        type: 'sales',
        customerId: 'CUST-006',
        orderDate: '2024-09-08',
        deliveryDate: '2024-09-24',
        quantity: 3,
        totalPrice: 1200,
        status: 'pending',
        productId: 'ID-021',
      },
      {
        id: 'PO-006',
        type: 'purchase',
        supplierId: 'SUP-013',
        orderDate: '2024-09-09',
        deliveryDate: '2024-09-30',
        quantity: 500,
        totalPrice: 12500,
        status: 'placed',
        productId: 'ID-013',
      },
    ];
  }

  getCampaigns(): Campaign[] {
    return [
      {
        id: 'CAMP-001',
        name: 'Spring Sale',
        type: 'seasonal',
        assignmentType: 'product',
        startDate: '2024-03-01',
        endDate: '2024-03-31',
        percentage: 20,
        productIds: ['ID-001', 'ID-012', 'ID-016'],
        customerIds: [],
        description: 'Spring seasonal discount on selected products',
        isActive: true,
      },
      {
        id: 'CAMP-002',
        name: 'VIP Customer Discount',
        type: 'promotion',
        assignmentType: 'customer',
        startDate: '2024-01-01',
        endDate: '2024-12-31',
        percentage: 15,
        productIds: [],
        customerIds: ['CUST-003', 'CUST-007', 'CUST-010'],
        description: 'Year-long discount for institutional customers',
        isActive: true,
      },
      {
        id: 'CAMP-003',
        name: 'Electronics Clearance',
        type: 'clearance',
        assignmentType: 'product',
        startDate: '2024-09-01',
        endDate: '2024-09-30',
        percentage: 35,
        productIds: ['ID-012', 'ID-016'],
        customerIds: [],
        description: 'End of season electronics clearance',
        isActive: true,
      },
      {
        id: 'CAMP-004',
        name: 'New Customer Welcome',
        type: 'promotion',
        assignmentType: 'customer',
        startDate: '2024-08-01',
        endDate: '2024-10-31',
        percentage: 10,
        productIds: [],
        customerIds: ['CUST-001', 'CUST-005', 'CUST-009'],
        description: 'Welcome discount for new individual customers',
        isActive: true,
      },
      {
        id: 'CAMP-005',
        name: 'Furniture Flash Sale',
        type: 'discount',
        assignmentType: 'product',
        startDate: '2024-09-15',
        endDate: '2024-09-22',
        percentage: 25,
        productIds: ['ID-017', 'ID-021'],
        customerIds: [],
        description: 'Limited time furniture discount',
        isActive: true,
      },
    ];
  }
}
