-- Core master data: products, suppliers, customers
CREATE TABLE products (
  product_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_name      VARCHAR(200) NOT NULL,
  description       TEXT,
  category          VARCHAR(100) NOT NULL,
  unit_of_measure   VARCHAR(20) DEFAULT 'adet',
  safety_stock      NUMERIC(10,2) DEFAULT 0,
  reorder_point     NUMERIC(10,2) DEFAULT 0,
  current_price NUMERIC(10,2) NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE suppliers (
  supplier_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_name     VARCHAR(200) NOT NULL,
  email             VARCHAR(100) NOT NULL UNIQUE,
  phone             VARCHAR(30) NOT NULL,
  city              VARCHAR(50) NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE customers (
  customer_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name     VARCHAR(200) NOT NULL,
  customer_segment  customer_segment NOT NULL,
  email             VARCHAR(100) NOT NULL UNIQUE,
  phone             VARCHAR(30) NOT NULL,
  city              VARCHAR(50) NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);
