spring:
  application:
    name: inventory

  # --- Database (PostgreSQL) ---
  datasource:
    url: jdbc:postgresql://${INVENTORY_DB_HOST:localhost}:${INVENTORY_DB_PORT:5432}/${INVENTORY_DB_NAME:inventory_db}
    username: ${INVENTORY_DB_USERNAME:admin}
    password: ${INVENTORY_DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  # --- JPA / Hibernate ---
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        '[format_sql]': true
        '[use_sql_comments]': true

# --- Server ---
server:
  port: ${SERVER_PORT:8000}
  servlet:
    context-path: /api/v1

# --- Logging ---
logging:
  level:
    '[com.petek.inventoryService]': INFO
    '[org.springframework.web]': INFO
    '[org.hibernate.SQL]': INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# ===== Development Profile (H2 in-memory) =====
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:inventory_dev;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true

logging:
  level:
    root: DEBUG
    '[com.petek.inventoryService]': DEBUG